export const MedicationActionTypes = {
  MERGE_MEDICATIONS: 'MERGE_MEDICATIONS',
  ADD_MEDICATION: 'ADD_MEDICATION',
  UPDATE_MEDICATION: 'UPDATE_MEDICATION',
  DELETE_MEDICATION: 'DELETE_MEDICATION',
}
