import {
  MOCK_API_ENDPOINT as ENV_MOCK_API_ENDPOINT,
  API_INDIA_ENDPOINT as ENV_API_INDIA_ENDPOINT,
  API_BANGLADESH_ENDPOINT as ENV_API_BANGLADESH_ENDPOINT,
  API_ETHIOPIA_ENDPOINT as ENV_API_ETHIOPIA_ENDPOINT,
} from 'react-native-dotenv'

console.log('ENV_API_INDIA_ENDPOINT >> ', ENV_API_INDIA_ENDPOINT)

export const API_INDIA_ENDPOINT: string = ENV_API_INDIA_ENDPOINT
export const API_BANGLADESH_ENDPOINT: string = ENV_API_BANGLADESH_ENDPOINT
export const API_ETHIOPIA_ENDPOINT: string = ENV_API_ETHIOPIA_ENDPOINT
export const MOCK_API_ENDPOINT: string = ENV_MOCK_API_ENDPOINT
