const ENGLISH = 'en'
const HINDI = 'hi'
const MARATHI = 'mr'
const PUNJABI = 'pa'

const AVAILABLE_TRANSLATIONS = [ENGLISH, HINDI, MARATHI, PUNJABI]
const DEFAULT_LANGUAGE = ENGLISH

export {
  ENGLISH,
  HINDI,
  MARATHI,
  PUNJABI,
  AVAILABLE_TRANSLATIONS,
  DEFAULT_LANGUAGE,
}
