const SCREENS = {
  LAUNCH: 'LAUNCH',
  MAIN_STACK: 'MAIN_STACK',
  SPLASH: 'SPLASH',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
  LOGIN: 'LOGIN',
  CONSENT: 'CONSENT',
  SCAN_BP_PASSPORT: 'SCAN_BP_PASSPORT',
  VERIFY_YOUR_NUMBER: 'VERIFY_YOUR_NUMBER',
  ALL_BP: 'ALL_BP',
  SETTINGS: 'SETTINGS',
  CONTACT_A_DOCTOR: 'CONTACT_A_DOCTOR',
}

export default SCREENS
