enum SCREENS {
  LAUNCH = 'LAUNCH',
  MAIN_STACK = 'MAIN_STACK',
  SPLASH = 'SPLASH',
  LOGIN = 'LOGIN',
  CONSENT = 'CONSENT',
  SCAN_BP_PASSPORT = 'SCAN_BP_PASSPORT',
  VERIFY_YOUR_NUMBER = 'VERIFY_YOUR_NUMBER',
  ALL_BP = 'ALL_BP',
  SETTINGS = 'SETTINGS',
  CONTACT_A_DOCTOR = 'CONTACT_A_DOCTOR',
  HOME = 'HOME',
  BP_HISTORY = 'BP_HISTORY',
  BP_DETAILS = 'BP_DETAILS',
  ADD_BP = 'ADD_BP',
  BS_HISTORY = 'BS_HISTORY',
  BS_DETAILS = 'BS_DETAILS',
  ADD_BS = 'ADD_BS',
  ADD_MEDICINE = 'ADD_MEDICINE',
}

export default SCREENS
