export const AuthActionTypes = {
  SET_API_ENDPOINT: 'SET_API_ENDPOINT',
  SET_AUTH_PARAMS: 'SET_AUTH_PARAMS',
  SET_LOGIN_STATE: 'SET_LOGIN_STATE',
  SET_PASSPORT_LINKED_STATE: 'SET_PASSPORT_LINKED_STATE',
  LOG_OUT: 'LOG_OUT',
}
