export const PatientActionTypes = {
  GET_PATIENT: 'GET_PATIENT',
  SET_PATIENT: 'SET_PATIENT',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_HAS_REVIEWED: 'SET_HAS_REVIEWED',
  SET_NORMAL_BP_COUNT: 'SET_NORMAL_BP_COUNT',
  SET_NORMAL_BS_COUNT: 'SET_NORMAL_BS_COUNT',
}
