export const NotificationsActionTypes = {
  NOTIFICATIONS_SET_PUSH_NOTIFICATION_PERMISSION:
    'NOTIFICATIONS_SET_PUSH_NOTIFICATION_PERMISSION',
  NOTIFICATIONS_SET_DEVICE_PUSH_TOKEN: 'NOTIFICATIONS_SET_DEVICE_PUSH_TOKEN',
}
